

class DatabaseException(Exception): ...
class PermissionAlreadyExists(Exception): ...
class PermissionFuncNotExists(Exception): ...
class SecurityException(Exception): ...
class EventsAlreadyRegisted(Exception): ...